# Generated by Django 5.1.3 on 2024-11-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guarder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='guarder-img/')),
            ],
        ),
    ]
