# Generated by Django 5.1.3 on 2024-11-23 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_icon_alter_service_body_alter_service_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
    ]
